### ISSUE TITLE
hasName() bug in EASYBLE

### ISSUE THREAD

**Issue by sjrcgtek** [evothings/evothings-libraries#15]
In the easyble.dist.js file:

		device.hasName = function(name)
		{
			// If there is a device name present in advertisement data,
			// check if this matches. (This name is not cached by iOS.)
			var deviceName = device.advertisementData ?
				device.advertisementData.kCBAdvDataLocalName : false;
			if (deviceName) 
			{ 
				return 0 == deviceName.indexOf(name);
			}
			
			// Otherwise check if device.name matches (cached by iOS,
			// might not match if device name is updated).
			return name = device.name;
		};

Don't you want == on that return statement?

Cheers!

**Comment by mikaelkindborg** [comment]
@sjrcgtek Thanks a lot for reporting! Fixed by these commits: https://github.com/evothings/evothings-libraries/commit/d962043c683987537eae6b6314a6340483dd14d2 https://github.com/evothings/evothings-libraries/commit/90a7bf461f403cbcfe7b8562a27ba5f0b1308483
